import type { GithubToolName } from '@github-tools/sdk';

export const ALLOWLIST: GithubToolName[] = [
  'addAssignees',
  'addIssueComment',
  'addLabels',
  'addPullRequestComment',
  'closeIssue',
  'compareCommits',
  'createIssue',
  'createPullRequest',
  'getCiFailureContext',
  'getCommit',
  'getFileContent',
  'getIssueContext',
  'getPullRequestContext',
  'getRepository',
  'getRepositoryTree',
  'listBranches',
  'listCheckRuns',
  'listCommits',
  'listIssueComments',
  'listIssues',
  'listLabels',
  'listPullRequestFiles',
  'listPullRequestReviews',
  'listPullRequests',
  'removeAssignees',
  'removeLabel',
  'requestReviewers',
  'searchCode',
  'searchIssues',
  'searchRepositories',
  'updateIssue',
  'updatePullRequest',
];
